In [626]:
import pandas as pd
from numpy.random import RandomState
from itertools import product

df=pd.DataFrame({'sentID':xrange(1,11)})


#ASSIGNER

def add_blocks(frame, size, name='block', condList=None, id_col=None, start_at=0):

    def _assigner(lim,size):
        num = 0
        n=0
        while n<=lim:
            if n % size == 0 and n != 0:
                num +=1
                n += 1
                print blocks[num],n, num
                yield blocks[num]
            else:
                n +=1
                print blocks[num],n,num
                yield blocks[num]

    if condList is None:
        blocks=range(len(frame)/size)
    else:
        blocks=condList
    
    assigner=_assigner(len(frame),size)

    def _add(chunk):
        chunk[name]=[assigner.next() for _ in xrange(len(chunk))]
        return chunk
    
    if id_col is None:
        new_frame=_add(frame).sort_values(by=name)
    else:
        new_frame=frame.groupby(id_col).apply(_add).sort_values(by=id_col)

    if condList is None:
        #new_frame[name]=new_frame[name]+start_at
        return new_frame
    else:
        new_frame[name]=new_frame[name]
        return new_frame

In [536]:
test=add_blocks(df,6,name='cond',condList=['fuck','you'])

In [526]:
test=add_blocks(df,5)

In [527]:
test

   sentID  cond  block
0       1  fuck      0
1       2  fuck      0
2       3  fuck      0
3       4  fuck      0
4       5  fuck      0
5       6   you      1
6       7   you      1
7       8   you      1
8       9   you      1
9      10   you      1

In [630]:
df=pd.DataFrame({'sentID':xrange(1,13)})
halfSplit=add_blocks(df,6,name='cond',condList=['fuck','this'])
thirdSplot=add_blocks(halfSplit,3,name='speaker', condList=['nat','non','nat','non'])
thirdSplot.sort_values(by='cond')

fuck 1 0
fuck 2 0
fuck 3 0
fuck 4 0
fuck 5 0
fuck 6 0
this 7 1
this 8 1
this 9 1
this 10 1
this 11 1
this 12 1
nat 1 0
nat 2 0
nat 3 0
non 4 1
non 5 1
non 6 1
nat 7 2
nat 8 2
nat 9 2
non 10 3
non 11 3
non 12 3

    sentID  cond speaker
0        1  fuck     nat
1        2  fuck     nat
2        3  fuck     nat
3        4  fuck     non
4        5  fuck     non
5        6  fuck     non
6        7  this     nat
7        8  this     nat
8        9  this     nat
9       10  this     non
10      11  this     non
11      12  this     non